const GET_USER_BALANCE = 'GET_USER_BALANCE';
const SEND_LIMIT_ORDER = 'SEND_LIMIT_ORDER';
const CANCEL_LIMIT_ORDER = 'CANCEL_LIMIT_ORDER';

export default {
  GET_USER_BALANCE,
  SEND_LIMIT_ORDER,
  CANCEL_LIMIT_ORDER,
};
