const SEND_LIMIT_ORDER = 'SEND_LIMIT_ORDER';
const CANCEL_LIMIT_ORDER = 'CANCEL_LIMIT_ORDER';
const CANCEL_ALL = 'CANCEL_ALL';

export default {
  SEND_LIMIT_ORDER,
  CANCEL_LIMIT_ORDER,
  CANCEL_ALL,
};
